# Generated by Django 3.0.8 on 2020-07-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlist_bids_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlist',
            old_name='image',
            new_name='image_url',
        ),
    ]
