# Generated by Django 3.0.8 on 2020-08-08 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionlist_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
