# Generated by Django 3.0.8 on 2020-08-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlist_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlist',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='auctionlist',
            old_name='item',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='item',
            new_name='prod',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='item',
            new_name='prod',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='item',
            new_name='prod',
        ),
    ]
