# Generated by Django 3.0.8 on 2020-08-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200809_1723'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'prod')},
        ),
    ]
