# Generated by Django 3.0.8 on 2020-08-11 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200809_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='sold_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bought', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
