# Generated by Django 3.0.8 on 2020-08-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200822_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='image_url',
            field=models.CharField(max_length=1000),
        ),
    ]
